server:
  port: 8080


ks:
  path: /Users/huluwa110/Desktop/ec-core/src/test/kestore/
  pdfdir: /Users/huluwa110/Desktop/ec-core/src/test/tmp/
  pdf:  test.pdf
  img:  /Users/huluwa110/Desktop/ec-core/src/test/tmp/pic.jpeg


